---
- name: Make terraform instance dir
  file: path="{{ terraform_instance_dir }}" state=directory

- name: "Get remote terraform.tfstate from s3"
  s3:
    aws_access_key: "{{ aws_key }}"
    aws_secret_key: "{{ aws_secret }}"
    region: "{{ aws_region }}"
    overwrite: different
    bucket: "{{ config_bucket }}"
    object: "{{ config_bucket_key }}"
    dest: "{{ terraform_instance_dir }}/terraform.tfstate"
    mode: get
  ignore_errors: yes
  when: terraform_s3_remote_enabled

- name: Generate terraform.tfvars file
  template: src=terraform.tfvars.jinja2
            dest="{{ terraform_instance_dir }}/terraform.tfvars"

- name: Run terraform apply or plan
  when: terraform_mode in ['apply', 'plan']
  shell: >
    terraform {{ terraform_mode }}
    -no-color
    -input=false
    -state={{ terraform_instance_dir }}/terraform.tfstate
    -var-file={{ terraform_instance_dir }}/terraform.tfvars
    chdir={{ terraform_dir }}
  ignore_errors: yes
  register: terraform_result_a

- name: Run terraform destroy
  when: terraform_mode in ['destroy']
  shell: >
    terraform {{ terraform_mode }}
    -force
    -refresh=false
    -no-color
    -input=false
    -state={{ terraform_instance_dir }}/terraform.tfstate
    -var-file={{ terraform_instance_dir }}/terraform.tfvars
    chdir={{ terraform_dir }}
  ignore_errors: yes
  register: terraform_result_b

- name: "Push remote terraform.tfstate"
  s3:
    aws_access_key: "{{ aws_key }}"
    aws_secret_key: "{{ aws_secret }}"
    region: "{{ aws_region }}"
    overwrite: different
    bucket: "{{ config_bucket }}"
    object: "{{ config_bucket_key }}"
    src: "{{ terraform_instance_dir }}/terraform.tfstate"
    mode: put
  when: terraform_s3_remote_enabled

- name: Dump terraform stderr on failure
  fail: msg="Terraform {{ terraform_mode }} failed with:\n{{ terraform_result_a.stderr }}"
  when: terraform_result_a|failed

- name: Dump terraform stderr on failure
  fail: msg="Terraform {{ terraform_mode }} failed with:\n{{ terraform_result_b.stderr }}"
  when: terraform_result_b|failed
