---
- name: Try updating jenkins jobs in jenkins container
  shell: docker exec {{ jenkins_container_name }} jenkins-jobs update --recursive --exclude /etc/jenkins_jobs/jobs/excluded-on-jenkins:/etc/jenkins_jobs/jobs/k2-configs /etc/jenkins_jobs
  register: result
  until: result.rc == 0
  retries: 5
  delay: 5
